# -*- coding: utf-8 -*-
"""knnearest-0-53.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YO6nEV4Cd5-Rm-CWhPZXRQk7A534fRVP
"""


import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


df2=pd.read_csv("../input/fraudaa/newdf2.csv")

ntese=pd.read_csv("../input/fraudaa/newtest.csv")
dte=pd.read_csv('../input/its-a-fraud/test.csv')

df2.drop(['Unnamed: 0'],axis=1,inplace=True)
ntese.drop(['Unnamed: 0'],axis=1,inplace=True)

X_test=ntese.copy()

df2.drop(['TransactionID'],axis=1,inplace=True)
X_test.drop(['TransactionID'],axis=1,inplace=True)

X=df2.drop(['isFraud'],axis=1,inplace=False)
y=df2['isFraud']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,stratify=y, test_size=0.33, random_state=42)


from sklearn.neighbors import KNeighborsClassifier

score=[0 for i in range(2,11)]
for k in range(2, 11):
    clf = KNeighborsClassifier(n_neighbors = k)
    clf.fit(X_res, y_res)
  
    test_score = clf.score(X_test, y_test)
    score[k]=test_score
score.append(test_score)

clf = KNeighborsClassifier(n_neighbors = 10)
clf.fit(X_res, y_res)
test_score = clf.score(X_test, y_test)

score.append(test_score)

from sklearn.neighbors import KNeighborsClassifier

knn=KNeighborsClassifier(n_neighbors=2)
knn.fit(X_res1,y_res1)

predhyp=knn.predict(X_test)

ntese['IsFraud']=predhyp

neww=ntese[['TransactionID','IsFraud']]

dte = dte.merge(neww, how='outer',copy=False, on ='TransactionID' )

y_predd=dte['IsFraud']

y_predd.to_csv('y_pred20.csv')

